MD @ECHO OFF

ECHO Creating user backup folder in vision2 directory ...
PUSHD \\vision2\backups
IF NOT EXIST .\%USERNAME%
    ECHO Creating %USERNAME% directory ...
    MD .\%USERNAME%
    ECHO Starting backup process ...
    POPD
    GOTO ROBO
ELSE ECHO %USERNAME% directory already exists ...
    ECHO Starting backup process ...
    POPD
    GOTO ROBO

:ROBO
    ECHO Copying user folders to vision2 directory ...
    RoboCopy.exe %USERPROFILE% \\vision2\backups\%USERNAME% *.* /S /COPY:DAT /XF *.DAT* *.dll* /XD *OneDrive* *AppData* *Application* /MT:16 /R:0 /V /ETA
